# Generated by Django 5.1.5 on 2025-02-07 16:53

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('country', models.CharField(blank=True, default='US', max_length=2)),
                ('preferred_providers', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='UserWatchList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('show_id', models.IntegerField()),
                ('season', models.IntegerField()),
                ('num_episodes_watched', models.IntegerField(blank=True, default=0)),
                ('datetime_added_at', models.DateTimeField(auto_now_add=True)),
                ('datetime_started_at', models.DateTimeField(blank=True, null=True)),
                ('datetime_finished_at', models.DateTimeField(blank=True, null=True)),
                ('num_delay_days', models.IntegerField(blank=True, default=0)),
                ('status', models.CharField(choices=[('Returning Series', 'Returning Series'), ('Planned', 'Planned'), ('In Production', 'In Production'), ('Ended', 'Ended'), ('Canceled', 'Canceled'), ('Pilot', 'Pilot')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UserWatchStats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('num_watched_episodes', models.IntegerField(default=0)),
                ('minutes_watched', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.userprofile')),
            ],
        ),
    ]
