# Generated by Django 5.1.5 on 2025-02-06 01:37

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('preferred_providers', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserWatchList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('show_id', models.IntegerField()),
                ('season', models.IntegerField()),
                ('num_episodes_watched', models.IntegerField(default=0)),
                ('datetime_added_at', models.DateTimeField(auto_now_add=True)),
                ('datetime_started_at', models.DateTimeField(blank=True, null=True)),
                ('datetime_finished_at', models.DateTimeField(blank=True, null=True)),
                ('num_delay_days', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('returning_series', 'Returning Series'), ('planned', 'Planned'), ('in_production', 'In Production'), ('ended', 'Ended'), ('canceled', 'Canceled'), ('pilot', 'Pilote')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserWatchStats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('num_watched_episodes', models.IntegerField(default=0)),
                ('minutes_watched', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
