# Generated by Django 5.1.5 on 2025-02-08 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userwatchlist',
            unique_together={('user', 'show_id', 'season')},
        ),
        migrations.AlterUniqueTogether(
            name='userwatchstats',
            unique_together={('user', 'date')},
        ),
    ]
