# Generated by Django 5.2.4 on 2025-07-27 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_userwatchlist_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwatchlist',
            name='datetime_removed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
