# Generated by Django 5.2.4 on 2025-08-01 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_userwatchlist_datetime_removed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
