# Generated by Django 5.2.4 on 2026-04-14 22:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_userprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ignored_providers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
    ]
